### ISSUE TITLE
Rexi highlighting wrapping lines

### ISSUE THREAD

**Issue by jshipley** [royreznik/rexi#11]
Running rexi 1.1.0 installed from pypi

After checking out rexi repository, run `rexi -i README.md`

When I start typing in a regex, highlighting is applied to the main box. If the regex is just a single `.` then all of the text gets wrapped and looks like this: ![rexi_wrapping](https://github.com/royreznik/rexi/assets/20493/ed896c81-e5f7-4df5-8dc5-676e8e89f369)

**Comment by royreznik** [comment]
Hi! Thanks for pointing it out,i will open a PR that will fix it later in the week 😀

**Comment by royreznik** [comment]
Fixed :)
