### ISSUE TITLE
Rexi stdin handling does not work on Windows

### ISSUE THREAD

**Issue by jshipley** [royreznik/rexi#12]
See https://www.reddit.com/r/Python/comments/1ahw7lj/rexi_a_terminal_ui_for_regex_testing_built_in/kpqx7v4/?context=3

I'm planning on submitting a pull request for this, but wanted to create an issue for it first.

rexi calling `select.select()` on Windows results in this error: "`OSError: [WinError 10038] An operation was attempted on something that is not a socket`"

This error is caused by this commit: https://github.com/royreznik/rexi/commit/e301ba3082b9157da3ee3fc2791867f3293697d4

I believe that this fix is the wrong approach to checking for input. The current behavior is to poll for data in stdin and then raise an error if there's no data.

A better approach would be to check if stdin is a tty. If it is a tty then you can quit with an error that no input is provided, but if it is not a tty (eg `echo "string to match" | rexi` or `rexi <README.me`) then the correct behaviour is to sit and wait for STDIN to terminate. This approach is both similar to how many other tools (like grep) work, and would work on Linux or on Windows.

Other than that, closing the pipe stdin and opening a /dev/tty stdin should work on Windows, but it will require using winpty.PTY instead of /dev/tty.

**Comment by royreznik** [comment]
Hi! I had some issues with checking for tty because the integration with 'typer', feel free to open a PR that will fix it!

Thanks
