### ISSUE TITLE
Packaging and distribuition

### ISSUE THREAD

**Issue by keysym** [royreznik/rexi#18]
I've distributed a packaging of rexi to ArchLinux/AUR and I'm creating this issues as requested on r/python thread.

https://aur.archlinux.org/packages/rexi

- Looking forward, how do you plan to package and distribute rexi?! Using CI/CD to package and then bumping the version on AUR?
- Do you want to co-maintain or have full ownership to rexi AUR package? If so, what's your account on AUR so I can proceed with this process?!
- Also, any plans to package for .deb, .rpm, flatpack, homebrew or Windows?

**Comment by royreznik** [comment]
@keysym 
1. Yes, i want to add CI/CD.
2. Please Transfer the ownership, my mail is "royreznik@gmail.com" and the account is "reznik"

**Comment by keysym** [comment]
As requested, I've transferred ownership of https://aur.archlinux.org/packages/rexi to @royreznik!

I have also dropped my maintainer status, but feel free to add me as a co-maintainer if needed.

**Comment by royreznik** [comment]
@keysym Thanks, will get in contact
