### ISSUE TITLE
Doesn't seem to work on macOS

### ISSUE THREAD

**Issue by espresso1736** [royreznik/rexi#19]
python 3.10.6, rexi installed in a clean virtual environment (using pip).  Let me know if you need more info.

<img width="730" alt="Screenshot 2024-02-27 at 3 57 20 PM" src="https://github.com/royreznik/rexi/assets/17815335/a690937b-c8b7-4f3a-bc3e-b6091ef02282">

Update: seems to be related to stdin.  Works ok if I specify --input and a file name.

**Comment by royreznik** [comment]
Hi! Thank for the issue.
i have never tried it on MacOS, so it may not work.

Would you like to open a PR that will make it work on MacOs?

**Comment by royreznik** [comment]
Hi there :) this should be fixed in version `1.1.3`, which just got released by @omerhadari , thank you.

**Comment by espresso1736** [comment]
Thanks!  Yes, seems to work great now.

Cheers!
Larry
